
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, filedialog


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/veleonlim/Downloads/build/assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("666x829")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 829,
    width = 666,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    39.0,
    118.0,
    199.0,
    278.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    242.0,
    119.0,
    402.0,
    279.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    131.0,
    410.0,
    572.0,
    716.0,
    fill="#D9D9D9",
    outline="")

canvas.create_text(
    39.0,
    92.0,
    anchor="nw",
    text="Cover Object / Stego",
    fill="#000000",
    font=("Inter", 12 * -1)
)

canvas.create_text(
    39.0,
    36.0,
    anchor="nw",
    text="Step 1: Upload File",
    fill="#000000",
    font=("Inter Bold", 12 * -1)
)

canvas.create_text(
    242.0,
    35.0,
    anchor="nw",
    text="Step 2: Upload Payload",
    fill="#000000",
    font=("Inter Bold", 12 * -1)
)

canvas.create_text(
    471.0,
    34.0,
    anchor="nw",
    text="Step 3: Select Number of LSB",
    fill="#000000",
    font=("Inter Bold", 12 * -1)
)

canvas.create_text(
    470.0,
    170.0,
    anchor="nw",
    text="Step 4: Encode or Decode",
    fill="#000000",
    font=("Inter Bold", 12 * -1)
)

canvas.create_text(
    242.0,
    92.0,
    anchor="nw",
    text="Payload",
    fill="#000000",
    font=("Inter", 12 * -1)
)

canvas.create_text(
    319.0,
    374.0,
    anchor="nw",
    text="Output",
    fill="#000000",
    font=("Inter", 12 * -1)
)

canvas.create_text(
    474.0,
    92.0,
    anchor="nw",
    text="Number of LSB (0-5)",
    fill="#000000",
    font=("Inter", 12 * -1)
)

# button_image_1 = PhotoImage(
#     file=relative_to_assets("button_1.png"))
button_1 = Button(
    # image=button_image_1,
    text="Upload",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: (upload_file(), print("button_1 clicked")),
    relief="flat"
)

button_1.place(
    x=116.0,
    y=305.0,
    width=83.0,
    height=35.0
)

# button_image_2 = PhotoImage(
#     file=relative_to_assets("button_2.png"))
button_2 = Button(
    # image=button_image_2,
    text="Upload",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: (upload_file(), print("button_1 clicked")),
    relief="flat"
)
button_2.place(
    x=318.0,
    y=305.0,
    width=83.0,
    height=35.0
)

# button_image_3 = PhotoImage(
#     file=relative_to_assets("button_3.png"))
button_3 = Button(
    # image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=472.0,
    y=206.0,
    width=152.0,
    height=35.0
)

# button_image_4 = PhotoImage(
#     file=relative_to_assets("button_4.png"))
button_4 = Button(
    # image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=472.0,
    y=258.0,
    width=152.0,
    height=34.0
)

canvas.create_rectangle(
    472.0,
    115.0,
    624.0,
    141.0,
    fill="#D9D9D9",
    outline="")


def upload_file():
    file = filedialog.askopenfile()
    fob = open(file, 'r')
    print(fob.read())
        
window.resizable(False, False)
window.mainloop()
